services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: triplanner
      MYSQL_USER: triplanner
      MYSQL_PASSWORD: triplanner123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 10s
      retries: 3
      start_period: 30s

  app:
    image: kjh0620/backend-app:latest
    container_name: springboot-app
    ports:
      - "8086:8086"
    depends_on:
      - mysql
    environment:
      SPRING_PROFILES_ACTIVE: docker

volumes:
  mysql_data:


